apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: boutiqueacr.azurecr.io/auth:be91cd535a86ef10b7d50e799288aad86ff66e1e
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3002"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: boutique-secrets
                  key: AUTH_DB_URL

--- 

apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: boutique
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
